include('modules/sv_antifreekill.lua')
include('modules/sv_command.lua')
include('modules/sv_config.lua')
include('modules/sv_core.lua')
include('modules/sv_fun.lua')
include('modules/sv_particles.lua')
include('modules/sv_rtd.lua')
include('modules/sv_sound.lua')
include('modules/sv_spectate.lua')
include('modules/sv_votemap.lua')

print('done.')